NAME = libft.a
PATH_SRC = ./src/
HEADER = ./includes/
CFLAGS = -Wall -Wextra - Werror -c
OPTION = -I $(HEADER)
SRCS = $(PATH_SRC)ft_putchar.c $(PATH_SRC)ft_putstr.c $(PATH_SRC)ft_strcmp.c $(PATH_SRC)ft_strlen.c $(PATH_SRC)ft_swap.c
OBJS = ft_putchar.o ft_putstr.o ft_strcmp.o ft_strlen.o ft_swap.o

all: $(NAME)

$(NAME):
	gcc $(CFLAGS) $(OPTION) $(SRCS)
	ar rc $(NAME) $(OBJS)

clean:
	/bin/rm -f $(OBJS)
fclean : clean
	/bin/rm -f $(NAME)

re: fclean all
